# SPDX-FileCopyrightText: 2017 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: CC0-1.0

version: 2

build:
  # This should mirror the configuration in ./.forgejo/workflows/test.yaml
  os: ubuntu-24.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - python -m pip install poetry
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m poetry install --with
        docs

sphinx:
  configuration: docs/conf.py
