# SPDX-FileCopyrightText: 2020 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Use fsfe/reuse:latest as a base, and install additional packages on top
FROM fsfe/reuse:latest

RUN apk --no-cache add openssh-client
