# SPDX-FileCopyrightText: 2023 Free Software Foundation Europe e.V.
# SPDX-FileCopyrightText: 2024 Skyler Grey <sky@a.starrysky.fyi>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Test with Jujutsu

# These tests are run exclusively on the main branch to reduce CPU time wasted
# on every single PR that very likely does not affect Jujutsu functionality.
on:
  push:
    branches:
      - main
    paths:
      - "src/reuse/**.py"
      - "tests/**.py"
jobs:
  test-jujutsu:
    runs-on: debian-trixie
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-poetry
          poetry install --no-interaction --only main,test
      - name: Set up Jujutsu
        run: |
          cargo install cargo-binstall
          cargo binstall --strategies crate-meta-data jj-cli --no-confirm
          export PATH=~/.cargo/bin:$PATH
      - name: Run tests with pytest
        run: |
          poetry run pytest -vv --cov=reuse
