# SPDX-FileCopyrightText: 2021 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Like normal Dockerfile, but based on python:slim (Debian) to ease compliance

# Create a base image that has dependencies installed.
FROM python:slim AS base

RUN apt-get update \
    && apt-get install -y git mercurial \
    && rm -rf /var/lib/apt/lists/*

# Build reuse into a virtualenv
FROM base AS build

RUN apt-get update \
    && apt-get install -y python3-dev python3-pip gettext \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry

WORKDIR /reuse-tool
COPY . /reuse-tool/

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN poetry install --no-interaction --no-dev --no-root
RUN poetry build --no-interaction
RUN pip install dist/*.whl

# Copy over the virtualenv and use it
FROM base
COPY --from=build /opt/venv /opt/venv

ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN git config --global --add safe.directory /data
WORKDIR /data

ENTRYPOINT ["reuse"]
CMD ["lint"]
