# SPDX-FileCopyrightText: 2021 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Like normal Dockerfile, but based on python:slim (Debian) to ease compliance

# Create a base image that has dependencies installed.
FROM python:slim AS base

RUN apt-get update \
    && apt-get install -y git mercurial python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Build reuse into a virtualenv
FROM base AS build

WORKDIR /reuse-tool

COPY . /reuse-tool/

RUN pip3 install "poetry>=1.2"
RUN poetry config virtualenvs.create false \
  && poetry install --without dev --no-interaction --no-ansi

WORKDIR /data

ENTRYPOINT ["reuse"]
CMD ["lint"]
