# SPDX-FileCopyrightText: 2025 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: pip install . --target build
      - run: ./zipapp.py
      - run: ./reuse.pyz --version
      - uses: actions/upload-artifact@v4
        with:
          name: reuse-app
          path: reuse.pyz

  publish:
    name: Publish Release
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v5
        with:
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          files: "*.pyz"
